#!/bin/bash

# echo "Removing old .msg files ..."
# rm -f ../../../bebop_autonomy_msgs/msg/autogenerated/*.msg
# echo "Installing .msg files ..."
# cp *.msg ../../../bebop_autonomy_msgs/msg/autogenerated
# echo "Removing old .h files ..."
# rm -f ../../../bebop_autonomy/include/bebop_autonomy/autogenerated/*.h
# echo "Installing .h files .."
# cp *.h ../../../bebop_autonomy/include/bebop_autonomy/autogenerated
# echo "Removing old .cfg files ..."
# rm -f ../../../bebop_autonomy/cfg/autogenerated/*.cfg
# echo "Installing cfg files ..."
# cp *.cfg ../../../bebop_autonomy/cfg/autogenerated
# chmod +x ../../../bebop_autonomy/cfg/autogenerated/*.cfg
echo "Removing old .rst files ..."
rm -f ../../../docs/autogenerated/*.rst
echo "Installing rst files ..."
cp *.rst ../../../docs/autogenerated/